### PR TITLE
send server chat now working

### PR DESCRIPTION
**Pull request by BigBrainTime**
I took a look at the http request from vrage in wireshark and figured out how to send a chat by just attaching a json file

### CODE REVIEW

**Comment by EchterTimo** [comment]
@BigBrainTime thank you for your commit. I really looked for this so long.
But it seems like this repo has been abandoned. ):

**Comment by BigBrainTime** [comment]
> @BigBrainTime thank you for your commit. I really looked for this so long. But it seems like this repo has been abandoned. ):

Unfortunately i believe you are right other wise this would have already been accepted. At least someone has found this helpful XD

**Comment by EchterTimo** [comment]
> > @BigBrainTime thank you for your commit. I really looked for this so long. But it seems like this repo has been abandoned. ):
> 
> Unfortunately i believe you are right other wise this would have already been accepted. At least someone has found this helpful XD

We could make a fork or own version of this if needed.

**Comment by BigBrainTime** [comment]
> > > @BigBrainTime thank you for your commit. I really looked for this so long. But it seems like this repo has been abandoned. ):
> > 
> > 
> > Unfortunately i believe you are right other wise this would have already been accepted. At least someone has found this helpful XD
> 
> We could make a fork or own version of this if needed.

Might be something to do once the SE2 comes out because I guarantee you they update VRAGE along with it. For now, at least this pull request is findable since you found it so I bet others have too.

**Comment by BSpendlove** [comment]
Hey guys, sorry I haven't played Space Engineers for quite some time, I've moved onto Satisfactory now days 😁

I can merge this request and make a new release so it's published as 1.0.2. I hadn't realize SE2 has been confirmed, might be my new fav game to play after I've played too much of Satisfactory when its released... :-)

**Comment by BSpendlove** [comment]
This has been released as v1.0.2 now:

https://pypi.org/project/vrage-api/1.0.2/

Let me know of any issues as I haven't had the chance to test it directly from a new python environment / pip install.

**Comment by EchterTimo** [comment]
> This has been released as v1.0.2 now:
> 
> https://pypi.org/project/vrage-api/1.0.2/
> 
> Let me know of any issues as I haven't had the chance to test it directly from a new python environment / pip install.

It works! Thank you! 🥳🎉

**Comment by BigBrainTime** [comment]
I might fork this again in the near future to do an httpx rewrite bc lets be honest most people are probably using this for an SE discord chat bot bc i know I did. Just happy it was finally recognized lol, only thing ive ever done a pull request on other than my own stuff for version control XD

**Comment by BigBrainTime** [comment]
Since I now know how i can contact you lol, how did you make this in the first place? i have managed to find ZERO helpful documentation on this every time i come back to it. The only thing ive managed to do that was helpful was watch the VRAGE clients network traffic but that is not something I want to do just to make this better.

**Comment by EchterTimo** [comment]
> Since I now know how i can contact you lol, how did you make this in the first place? i have managed to find ZERO helpful documentation on this every time i come back to it. The only thing ive managed to do that was helpful was watch the VRAGE clients network traffic but that is not something I want to do just to make this better.

I guess this might be the only way since Keen didnt make this api for direct access.

You can contact me on my discord. I might be able to help.

the name is EchterTimo

**Comment by BSpendlove** [comment]
There was this random screenshot of a spreadsheet:

image

at https://www.spaceengineersgame.com/dedicated-servers/

Which I used to build the API endpoints, and then I just kept reading the errors that were sent back for the missing fields and built it from there, the documentation was near to none

**Comment by BigBrainTime** [comment]
looking at this, i have an idea. did you try getting just v1 or v1/docs or anything like that in an attempt to find docs that way?

**Comment by BigBrainTime** [comment]
I tried my idea and got errors in return XD

i also started the httpx rewrite. i probably missed something but my limited testing shows i did it succesfully in under 15 minutes lol.

https://github.com/BigBrainTime/vrage_api/tree/httpx-rewrite

not putting a pull request bc that would break things for obvious reasons unless you want to open up a new branch i can submit my changes to seeing as how this is your project

**Comment by EchterTimo** [comment]
@BigBrainTime 
@BSpendlove 

Hey guys,
it's been a while...
I just wanted to let you know that I started development on a Go api client for the VRage API.

<https://github.com/space-engineers-tools/go-vrage>
[Repo Card](https://github.com/space-engineers-tools/go-vrage)

The project is still in its early stages, but I wanted to share it with you and get your feedback.
Maybe you might even want to contribute to the project, if you are interested in Go and/or the VRage API.

The reason why I started this project is that I wanted to learn Go and I thought it would be a good idea to create a client for the VRage API, since I am already familiar with it. Also I am planning to make another project that will use this client, so I thought it would be a good idea to create it first.

The newly created organization [space-engineers-tools](https://github.com/space-engineers-tools) can be a place for other tools related to Space Engineers, so if you have any ideas or even want to be part of the organization, feel free to reach out to me.

Maybe the mentioned httpx rewrite for the python client could be a good addition to the organization.

Greetings,
Timo

**Pull request merged**
